spring.application.name=backend
<<<<<<< Updated upstream
=======

spring.config.import=optional:classpath:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_ID}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true


server.port=7000